(function_item name: (identifier) @def.function)
(struct_item name: (type_identifier) @def.struct)
(enum_item name: (type_identifier) @def.enum)
(trait_item name: (type_identifier) @def.trait)
(impl_item body: (declaration_list (function_item name: (identifier) @def.method)))
(use_declaration argument: (_) @import.path)
(call_expression function: (identifier) @call.callee)
(call_expression function: (scoped_identifier name: (identifier) @call.callee))
